CREATE TABLE tb_lyric_chord (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                lyric_id UUID NOT NULL,
                                chord_id BIGINT NOT NULL,
                                position INT NOT NULL,

                                CONSTRAINT fk_lc_lyric FOREIGN KEY (lyric_id) REFERENCES tb_lyric(id),
                                CONSTRAINT fk_lc_chord FOREIGN KEY (chord_id) REFERENCES tb_chord(id)
);
