CREATE TABLE IF NOT EXISTS tb_comments (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           body VARCHAR(280) NOT NULL,
                                           likes BIGINT DEFAULT 0,

                                           author_id UUID NOT NULL,
                                           music_id UUID NOT NULL,

                                           parent_id BIGINT NULL,

                                           created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                                           updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

                                           CONSTRAINT fk_comment_author
                                               FOREIGN KEY (author_id) REFERENCES tb_user(id),

                                           CONSTRAINT fk_comment_music
                                               FOREIGN KEY (music_id) REFERENCES tb_music(id),

                                           CONSTRAINT fk_comment_parent
                                               FOREIGN KEY (parent_id) REFERENCES tb_comments(id)
);
